### ISSUE TITLE
Kullanım rehberi

### ISSUE THREAD

**Issue by mesudi37** [MimBinFikret/Turki#1]
S.A. Merhaba Hocam, Bu yazılım diline aşina olmayanlar için projeye bir kurulum rehberi hazırlarsanız güzel olur naçizane görüşüm.

**Comment by gitmuhammedalbayrak** [comment]
Aleyküm selam, kurusa bakmayın hocam, açtığınız issue'yu yeni gördüm: inşallah ilgileneceğim.

**Comment by gitmuhammedalbayrak** [comment]
@mesudi37 hocam bir Readme.md dosyası ekledim. Hızlıca şunu söylemem gerekebilir: Eğer sisteminizde GCC ve MAKE uygulamaları yoksa indirip PATH'ınıza eklemeniz gerekir. Ardından talimatlara uyarak uygulamayı derleyip çalıştırabilirsiniz.
